--DROP USER C##PDBUSER;

CREATE USER PDBUSER IDENTIFIED BY "1";

GRANT ADMINISTER ANY SQL TUNING SET TO PDBUSER;

GRANT ADMINISTER DATABASE TRIGGER TO PDBUSER;

BEGIN
SYS.DBMS_RESOURCE_MANAGER_PRIVS.GRANT_SYSTEM_PRIVILEGE
  (GRANTEE_NAME   => 'PDBUSER', 
   PRIVILEGE_NAME => 'ADMINISTER_RESOURCE_MANAGER',
   ADMIN_OPTION   => FALSE);
END;
/

GRANT ADMINISTER SQL MANAGEMENT OBJECT TO PDBUSER;

GRANT ADMINISTER SQL TUNING SET TO PDBUSER;

GRANT ADVISOR TO PDBUSER;

GRANT ALTER ANY ASSEMBLY TO PDBUSER;

GRANT ALTER ANY CLUSTER TO PDBUSER;

GRANT ALTER ANY CUBE TO PDBUSER;

GRANT ALTER ANY CUBE BUILD PROCESS TO PDBUSER;

GRANT ALTER ANY CUBE DIMENSION TO PDBUSER;

GRANT ALTER ANY DIMENSION TO PDBUSER;

GRANT ALTER ANY EDITION TO PDBUSER;

BEGIN
SYS.DBMS_RULE_ADM.GRANT_SYSTEM_PRIVILEGE(
  PRIVILEGE    => SYS.DBMS_RULE_ADM.ALTER_ANY_EVALUATION_CONTEXT,
  GRANTEE      => 'PDBUSER',
  GRANT_OPTION => TRUE);
END;
/

GRANT ALTER ANY INDEX TO PDBUSER;

GRANT ALTER ANY INDEXTYPE TO PDBUSER;

GRANT ALTER ANY LIBRARY TO PDBUSER;

GRANT ALTER ANY MATERIALIZED VIEW TO PDBUSER;

GRANT ALTER ANY MEASURE FOLDER TO PDBUSER;

GRANT ALTER ANY MINING MODEL TO PDBUSER;

GRANT ALTER ANY OPERATOR TO PDBUSER;

GRANT ALTER ANY OUTLINE TO PDBUSER;

GRANT ALTER ANY PROCEDURE TO PDBUSER;

GRANT ALTER ANY ROLE TO PDBUSER;

BEGIN
SYS.DBMS_RULE_ADM.GRANT_SYSTEM_PRIVILEGE(
  PRIVILEGE    => SYS.DBMS_RULE_ADM.ALTER_ANY_RULE,
  GRANTEE      => 'PDBUSER',
  GRANT_OPTION => TRUE);
END;
/

BEGIN
SYS.DBMS_RULE_ADM.GRANT_SYSTEM_PRIVILEGE(
  PRIVILEGE    => SYS.DBMS_RULE_ADM.ALTER_ANY_RULE_SET,
  GRANTEE      => 'PDBUSER',
  GRANT_OPTION => TRUE);
END;
/

GRANT ALTER ANY SEQUENCE TO PDBUSER;

GRANT ALTER ANY SQL PROFILE TO PDBUSER;

GRANT ALTER ANY SQL TRANSLATION PROFILE TO PDBUSER;

GRANT ALTER ANY TABLE TO PDBUSER;

GRANT ALTER ANY TRIGGER TO PDBUSER;

GRANT ALTER ANY TYPE TO PDBUSER;

GRANT ALTER DATABASE TO PDBUSER;

GRANT ALTER PROFILE TO PDBUSER;

GRANT ALTER RESOURCE COST TO PDBUSER;

GRANT ALTER ROLLBACK SEGMENT TO PDBUSER;

GRANT ALTER SESSION TO PDBUSER;

GRANT ALTER SYSTEM TO PDBUSER;

GRANT ALTER TABLESPACE TO PDBUSER;

GRANT ALTER USER TO PDBUSER;

GRANT ANALYZE ANY TO PDBUSER;

GRANT AUDIT ANY TO PDBUSER;

GRANT AUDIT SYSTEM TO PDBUSER;

GRANT BACKUP ANY TABLE TO PDBUSER;

GRANT BECOME USER TO PDBUSER;

GRANT CHANGE NOTIFICATION TO PDBUSER;

GRANT COMMENT ANY MINING MODEL TO PDBUSER;

GRANT COMMENT ANY TABLE TO PDBUSER;

GRANT CREATE ANY ASSEMBLY TO PDBUSER;

GRANT CREATE ANY CLUSTER TO PDBUSER;

GRANT CREATE ANY CONTEXT TO PDBUSER;

GRANT CREATE ANY CREDENTIAL TO PDBUSER;

GRANT CREATE ANY CUBE TO PDBUSER;

GRANT CREATE ANY CUBE BUILD PROCESS TO PDBUSER;

GRANT CREATE ANY CUBE DIMENSION TO PDBUSER;

GRANT CREATE ANY DIMENSION TO PDBUSER;

GRANT CREATE ANY DIRECTORY TO PDBUSER;

GRANT CREATE ANY EDITION TO PDBUSER;

BEGIN
SYS.DBMS_RULE_ADM.GRANT_SYSTEM_PRIVILEGE(
  PRIVILEGE    => SYS.DBMS_RULE_ADM.CREATE_ANY_EVALUATION_CONTEXT,
  GRANTEE      => 'PDBUSER',
  GRANT_OPTION => TRUE);
END;
/

GRANT CREATE ANY INDEX TO PDBUSER;

GRANT CREATE ANY INDEXTYPE TO PDBUSER;

GRANT CREATE ANY JOB TO PDBUSER;

GRANT CREATE ANY LIBRARY TO PDBUSER;

GRANT CREATE ANY MATERIALIZED VIEW TO PDBUSER;

GRANT CREATE ANY MEASURE FOLDER TO PDBUSER;

GRANT CREATE ANY MINING MODEL TO PDBUSER;

GRANT CREATE ANY OPERATOR TO PDBUSER;

GRANT CREATE ANY OUTLINE TO PDBUSER;

GRANT CREATE ANY PROCEDURE TO PDBUSER;

BEGIN
SYS.DBMS_RULE_ADM.GRANT_SYSTEM_PRIVILEGE(
  PRIVILEGE    => SYS.DBMS_RULE_ADM.CREATE_ANY_RULE,
  GRANTEE      => 'PDBUSER',
  GRANT_OPTION => TRUE);
END;
/

BEGIN
SYS.DBMS_RULE_ADM.GRANT_SYSTEM_PRIVILEGE(
  PRIVILEGE    => SYS.DBMS_RULE_ADM.CREATE_ANY_RULE_SET,
  GRANTEE      => 'PDBUSER',
  GRANT_OPTION => TRUE);
END;
/

GRANT CREATE ANY SEQUENCE TO PDBUSER;

GRANT CREATE ANY SQL PROFILE TO PDBUSER;

GRANT CREATE ANY SQL TRANSLATION PROFILE TO PDBUSER;

GRANT CREATE ANY SYNONYM TO PDBUSER;

GRANT CREATE ANY TABLE TO PDBUSER;

GRANT CREATE ANY TRIGGER TO PDBUSER;

GRANT CREATE ANY TYPE TO PDBUSER;

GRANT CREATE ANY VIEW TO PDBUSER;

GRANT CREATE ASSEMBLY TO PDBUSER;

GRANT CREATE CLUSTER TO PDBUSER;

GRANT CREATE CREDENTIAL TO PDBUSER;

GRANT CREATE CUBE TO PDBUSER;

GRANT CREATE CUBE BUILD PROCESS TO PDBUSER;

GRANT CREATE CUBE DIMENSION TO PDBUSER;

GRANT CREATE DATABASE LINK TO PDBUSER;

GRANT CREATE DIMENSION TO PDBUSER;

BEGIN
SYS.DBMS_RULE_ADM.GRANT_SYSTEM_PRIVILEGE(
  PRIVILEGE    => SYS.DBMS_RULE_ADM.CREATE_EVALUATION_CONTEXT_OBJ,
  GRANTEE      => 'PDBUSER',
  GRANT_OPTION => TRUE);
END;
/

GRANT CREATE EXTERNAL JOB TO PDBUSER;

GRANT CREATE INDEXTYPE TO PDBUSER;

GRANT CREATE JOB TO PDBUSER;

GRANT CREATE LIBRARY TO PDBUSER;

GRANT CREATE MATERIALIZED VIEW TO PDBUSER;

GRANT CREATE MEASURE FOLDER TO PDBUSER;

GRANT CREATE MINING MODEL TO PDBUSER;

GRANT CREATE OPERATOR TO PDBUSER;

GRANT CREATE PLUGGABLE DATABASE TO PDBUSER;

GRANT CREATE PROCEDURE TO PDBUSER;

GRANT CREATE PROFILE TO PDBUSER;

GRANT CREATE PUBLIC DATABASE LINK TO PDBUSER;

GRANT CREATE PUBLIC SYNONYM TO PDBUSER;

GRANT CREATE ROLE TO PDBUSER;

GRANT CREATE ROLLBACK SEGMENT TO PDBUSER;

BEGIN
SYS.DBMS_RULE_ADM.GRANT_SYSTEM_PRIVILEGE(
  PRIVILEGE    => SYS.DBMS_RULE_ADM.CREATE_RULE_OBJ,
  GRANTEE      => 'PDBUSER',
  GRANT_OPTION => TRUE);
END;
/

BEGIN
SYS.DBMS_RULE_ADM.GRANT_SYSTEM_PRIVILEGE(
  PRIVILEGE    => SYS.DBMS_RULE_ADM.CREATE_RULE_SET_OBJ,
  GRANTEE      => 'PDBUSER',
  GRANT_OPTION => TRUE);
END;
/

GRANT CREATE SEQUENCE TO PDBUSER;

GRANT CREATE SESSION TO PDBUSER;

GRANT CREATE SQL TRANSLATION PROFILE TO PDBUSER;

GRANT CREATE SYNONYM TO PDBUSER;

GRANT CREATE TABLE TO PDBUSER;

GRANT CREATE TABLESPACE TO PDBUSER;

GRANT CREATE TRIGGER TO PDBUSER;

GRANT CREATE TYPE TO PDBUSER;

GRANT CREATE USER TO PDBUSER;

GRANT CREATE VIEW TO PDBUSER;

GRANT DEBUG ANY PROCEDURE TO PDBUSER;

GRANT DEBUG CONNECT SESSION TO PDBUSER;

GRANT DELETE ANY CUBE DIMENSION TO PDBUSER;

GRANT DELETE ANY MEASURE FOLDER TO PDBUSER;

GRANT DELETE ANY TABLE TO PDBUSER WITH ADMIN OPTION;

BEGIN
SYS.DBMS_AQADM.GRANT_SYSTEM_PRIVILEGE (
  PRIVILEGE    => 'DEQUEUE_ANY',
  GRANTEE      => 'PDBUSER',
  ADMIN_OPTION => TRUE);
END;
/

GRANT DROP ANY ASSEMBLY TO PDBUSER;

GRANT DROP ANY CLUSTER TO PDBUSER;

GRANT DROP ANY CONTEXT TO PDBUSER;

GRANT DROP ANY CUBE TO PDBUSER;

GRANT DROP ANY CUBE BUILD PROCESS TO PDBUSER;

GRANT DROP ANY CUBE DIMENSION TO PDBUSER;

GRANT DROP ANY DIMENSION TO PDBUSER;

GRANT DROP ANY DIRECTORY TO PDBUSER;

GRANT DROP ANY EDITION TO PDBUSER;

BEGIN
SYS.DBMS_RULE_ADM.GRANT_SYSTEM_PRIVILEGE(
  PRIVILEGE    => SYS.DBMS_RULE_ADM.DROP_ANY_EVALUATION_CONTEXT,
  GRANTEE      => 'PDBUSER',
  GRANT_OPTION => TRUE);
END;
/

GRANT DROP ANY INDEX TO PDBUSER;

GRANT DROP ANY INDEXTYPE TO PDBUSER;

GRANT DROP ANY LIBRARY TO PDBUSER;

GRANT DROP ANY MATERIALIZED VIEW TO PDBUSER;

GRANT DROP ANY MEASURE FOLDER TO PDBUSER;

GRANT DROP ANY MINING MODEL TO PDBUSER;

GRANT DROP ANY OPERATOR TO PDBUSER;

GRANT DROP ANY OUTLINE TO PDBUSER;

GRANT DROP ANY PROCEDURE TO PDBUSER;

GRANT DROP ANY ROLE TO PDBUSER;

BEGIN
SYS.DBMS_RULE_ADM.GRANT_SYSTEM_PRIVILEGE(
  PRIVILEGE    => SYS.DBMS_RULE_ADM.DROP_ANY_RULE,
  GRANTEE      => 'PDBUSER',
  GRANT_OPTION => TRUE);
END;
/

BEGIN
SYS.DBMS_RULE_ADM.GRANT_SYSTEM_PRIVILEGE(
  PRIVILEGE    => SYS.DBMS_RULE_ADM.DROP_ANY_RULE_SET,
  GRANTEE      => 'PDBUSER',
  GRANT_OPTION => TRUE);
END;
/

GRANT DROP ANY SEQUENCE TO PDBUSER;

GRANT DROP ANY SQL PROFILE TO PDBUSER;

GRANT DROP ANY SQL TRANSLATION PROFILE TO PDBUSER;

GRANT DROP ANY SYNONYM TO PDBUSER;

GRANT DROP ANY TABLE TO PDBUSER;

GRANT DROP ANY TRIGGER TO PDBUSER;

GRANT DROP ANY TYPE TO PDBUSER;

GRANT DROP ANY VIEW TO PDBUSER;

GRANT DROP PROFILE TO PDBUSER;

GRANT DROP PUBLIC DATABASE LINK TO PDBUSER;

GRANT DROP PUBLIC SYNONYM TO PDBUSER;

GRANT DROP ROLLBACK SEGMENT TO PDBUSER;

GRANT DROP TABLESPACE TO PDBUSER;

GRANT DROP USER TO PDBUSER;

GRANT EM EXPRESS CONNECT TO PDBUSER;

BEGIN
SYS.DBMS_AQADM.GRANT_SYSTEM_PRIVILEGE (
  PRIVILEGE    => 'ENQUEUE_ANY',
  GRANTEE      => 'PDBUSER',
  ADMIN_OPTION => TRUE);
END;
/

GRANT EXECUTE ANY ASSEMBLY TO PDBUSER;

GRANT EXECUTE ANY CLASS TO PDBUSER;

BEGIN
SYS.DBMS_RULE_ADM.GRANT_SYSTEM_PRIVILEGE(
  PRIVILEGE    => SYS.DBMS_RULE_ADM.EXECUTE_ANY_EVALUATION_CONTEXT,
  GRANTEE      => 'PDBUSER',
  GRANT_OPTION => TRUE);
END;
/

GRANT EXECUTE ANY INDEXTYPE TO PDBUSER;

GRANT EXECUTE ANY LIBRARY TO PDBUSER;

GRANT EXECUTE ANY OPERATOR TO PDBUSER;

GRANT EXECUTE ANY PROCEDURE TO PDBUSER;

GRANT EXECUTE ANY PROGRAM TO PDBUSER;

BEGIN
SYS.DBMS_RULE_ADM.GRANT_SYSTEM_PRIVILEGE(
  PRIVILEGE    => SYS.DBMS_RULE_ADM.EXECUTE_ANY_RULE,
  GRANTEE      => 'PDBUSER',
  GRANT_OPTION => TRUE);
END;
/

BEGIN
SYS.DBMS_RULE_ADM.GRANT_SYSTEM_PRIVILEGE(
  PRIVILEGE    => SYS.DBMS_RULE_ADM.EXECUTE_ANY_RULE_SET,
  GRANTEE      => 'PDBUSER',
  GRANT_OPTION => TRUE);
END;
/

GRANT EXECUTE ANY TYPE TO PDBUSER;

GRANT EXECUTE ASSEMBLY TO PDBUSER;

GRANT EXEMPT DDL REDACTION POLICY TO PDBUSER;

GRANT EXEMPT DML REDACTION POLICY TO PDBUSER;

GRANT EXPORT FULL DATABASE TO PDBUSER;

GRANT FLASHBACK ANY TABLE TO PDBUSER;

GRANT FLASHBACK ARCHIVE ADMINISTER TO PDBUSER;

GRANT FORCE ANY TRANSACTION TO PDBUSER;

GRANT FORCE TRANSACTION TO PDBUSER;

GRANT GLOBAL QUERY REWRITE TO PDBUSER;

GRANT GRANT ANY OBJECT PRIVILEGE TO PDBUSER;

GRANT GRANT ANY PRIVILEGE TO PDBUSER;

GRANT GRANT ANY ROLE TO PDBUSER;

GRANT IMPORT FULL DATABASE TO PDBUSER;

GRANT INHERIT ANY PRIVILEGES TO PDBUSER;

GRANT INSERT ANY CUBE DIMENSION TO PDBUSER;

GRANT INSERT ANY MEASURE FOLDER TO PDBUSER;

GRANT INSERT ANY TABLE TO PDBUSER WITH ADMIN OPTION;

GRANT LOCK ANY TABLE TO PDBUSER;

GRANT LOGMINING TO PDBUSER;

GRANT MANAGE ANY FILE GROUP TO PDBUSER;

BEGIN
SYS.DBMS_AQADM.GRANT_SYSTEM_PRIVILEGE (
  PRIVILEGE    => 'MANAGE_ANY',
  GRANTEE      => 'PDBUSER',
  ADMIN_OPTION => TRUE);
END;
/

GRANT MANAGE FILE GROUP TO PDBUSER;

GRANT MANAGE SCHEDULER TO PDBUSER;

GRANT MANAGE TABLESPACE TO PDBUSER;

GRANT MERGE ANY VIEW TO PDBUSER;

GRANT ON COMMIT REFRESH TO PDBUSER;

GRANT QUERY REWRITE TO PDBUSER;

GRANT READ ANY FILE GROUP TO PDBUSER;

GRANT REDEFINE ANY TABLE TO PDBUSER;

GRANT RESTRICTED SESSION TO PDBUSER;

GRANT RESUMABLE TO PDBUSER;

GRANT SELECT ANY CUBE TO PDBUSER;

GRANT SELECT ANY CUBE BUILD PROCESS TO PDBUSER;

GRANT SELECT ANY CUBE DIMENSION TO PDBUSER;

GRANT SELECT ANY MEASURE FOLDER TO PDBUSER;

GRANT SELECT ANY MINING MODEL TO PDBUSER;

GRANT SELECT ANY SEQUENCE TO PDBUSER;

GRANT SELECT ANY TABLE TO PDBUSER WITH ADMIN OPTION;

GRANT SELECT ANY TRANSACTION TO PDBUSER;

GRANT SET CONTAINER TO PDBUSER;

REVOKE SYSDBA FROM PDBUSER;

GRANT SYSDBA TO PDBUSER WITH ADMIN OPTION;

REVOKE SYSOPER FROM PDBUSER;

GRANT SYSOPER TO PDBUSER WITH ADMIN OPTION;

GRANT UNDER ANY TABLE TO PDBUSER;

GRANT UNDER ANY TYPE TO PDBUSER;

GRANT UNDER ANY VIEW TO PDBUSER;

GRANT UNLIMITED TABLESPACE TO PDBUSER;

GRANT UPDATE ANY CUBE TO PDBUSER;

GRANT UPDATE ANY CUBE BUILD PROCESS TO PDBUSER;

GRANT UPDATE ANY CUBE DIMENSION TO PDBUSER;

GRANT UPDATE ANY TABLE TO PDBUSER WITH ADMIN OPTION;

GRANT USE ANY SQL TRANSLATION PROFILE TO PDBUSER;


GRANT "ADM_PARALLEL_EXECUTE_TASK" TO PDBUSER WITH ADMIN OPTION;
GRANT "APEX_ADMINISTRATOR_ROLE" TO PDBUSER WITH ADMIN OPTION;
GRANT "APEX_GRANTS_FOR_NEW_USERS_ROLE" TO PDBUSER WITH ADMIN OPTION;
GRANT "AQ_ADMINISTRATOR_ROLE" TO PDBUSER WITH ADMIN OPTION;
GRANT "AQ_USER_ROLE" TO PDBUSER WITH ADMIN OPTION;
GRANT "AUDIT_ADMIN" TO PDBUSER WITH ADMIN OPTION;
GRANT "AUDIT_VIEWER" TO PDBUSER WITH ADMIN OPTION;
GRANT "AUTHENTICATEDUSER" TO PDBUSER WITH ADMIN OPTION;
GRANT "CAPTURE_ADMIN" TO PDBUSER WITH ADMIN OPTION;
GRANT "CDB_DBA" TO PDBUSER WITH ADMIN OPTION;
GRANT "CONNECT" TO PDBUSER WITH ADMIN OPTION;
GRANT "CSW_USR_ROLE" TO PDBUSER WITH ADMIN OPTION;
GRANT "CTXAPP" TO PDBUSER WITH ADMIN OPTION;
GRANT "DATAPUMP_EXP_FULL_DATABASE" TO PDBUSER WITH ADMIN OPTION;
GRANT "DATAPUMP_IMP_FULL_DATABASE" TO PDBUSER WITH ADMIN OPTION;
GRANT "DBA" TO PDBUSER WITH ADMIN OPTION;
GRANT "DBFS_ROLE" TO PDBUSER WITH ADMIN OPTION;
GRANT "DBHADOOP" TO PDBUSER WITH ADMIN OPTION;
GRANT "DELETE_CATALOG_ROLE" TO PDBUSER WITH ADMIN OPTION;
GRANT "DV_REALM_OWNER" TO PDBUSER WITH ADMIN OPTION;
GRANT "DV_REALM_RESOURCE" TO PDBUSER WITH ADMIN OPTION;
GRANT "EJBCLIENT" TO PDBUSER WITH ADMIN OPTION;
GRANT "EM_EXPRESS_ALL" TO PDBUSER WITH ADMIN OPTION;
GRANT "EM_EXPRESS_BASIC" TO PDBUSER WITH ADMIN OPTION;
GRANT "EXECUTE_CATALOG_ROLE" TO PDBUSER WITH ADMIN OPTION;
GRANT "EXP_FULL_DATABASE" TO PDBUSER WITH ADMIN OPTION;
GRANT "GATHER_SYSTEM_STATISTICS" TO PDBUSER WITH ADMIN OPTION;
GRANT "GDS_CATALOG_SELECT" TO PDBUSER WITH ADMIN OPTION;
GRANT "GSMADMIN_ROLE" TO PDBUSER WITH ADMIN OPTION;
GRANT "GSMUSER_ROLE" TO PDBUSER WITH ADMIN OPTION;
GRANT "GSM_POOLADMIN_ROLE" TO PDBUSER WITH ADMIN OPTION;
GRANT "HS_ADMIN_EXECUTE_ROLE" TO PDBUSER WITH ADMIN OPTION;
GRANT "HS_ADMIN_ROLE" TO PDBUSER WITH ADMIN OPTION;
GRANT "HS_ADMIN_SELECT_ROLE" TO PDBUSER WITH ADMIN OPTION;
GRANT "IMP_FULL_DATABASE" TO PDBUSER WITH ADMIN OPTION;
GRANT "JAVADEBUGPRIV" TO PDBUSER WITH ADMIN OPTION;
GRANT "JAVAIDPRIV" TO PDBUSER WITH ADMIN OPTION;
GRANT "JAVASYSPRIV" TO PDBUSER WITH ADMIN OPTION;
GRANT "JAVAUSERPRIV" TO PDBUSER WITH ADMIN OPTION;
GRANT "JAVA_ADMIN" TO PDBUSER WITH ADMIN OPTION;
GRANT "JAVA_DEPLOY" TO PDBUSER WITH ADMIN OPTION;
GRANT "JMXSERVER" TO PDBUSER WITH ADMIN OPTION;
GRANT "LBAC_DBA" TO PDBUSER WITH ADMIN OPTION;
GRANT "LOGSTDBY_ADMINISTRATOR" TO PDBUSER WITH ADMIN OPTION;
GRANT "OEM_ADVISOR" TO PDBUSER WITH ADMIN OPTION;
GRANT "OEM_MONITOR" TO PDBUSER WITH ADMIN OPTION;
GRANT "OLAP_DBA" TO PDBUSER WITH ADMIN OPTION;
GRANT "OLAP_USER" TO PDBUSER WITH ADMIN OPTION;
GRANT "OLAP_XS_ADMIN" TO PDBUSER WITH ADMIN OPTION;
GRANT "OPTIMIZER_PROCESSING_RATE" TO PDBUSER WITH ADMIN OPTION;
GRANT "ORDADMIN" TO PDBUSER WITH ADMIN OPTION;
GRANT "PDB_DBA" TO PDBUSER WITH ADMIN OPTION;
GRANT "PROVISIONER" TO PDBUSER WITH ADMIN OPTION;
GRANT "RECOVERY_CATALOG_OWNER" TO PDBUSER WITH ADMIN OPTION;
GRANT "RESOURCE" TO PDBUSER WITH ADMIN OPTION;
GRANT "SCHEDULER_ADMIN" TO PDBUSER WITH ADMIN OPTION;
GRANT "SELECT_CATALOG_ROLE" TO PDBUSER WITH ADMIN OPTION;
GRANT "SPATIAL_CSW_ADMIN" TO PDBUSER WITH ADMIN OPTION;
GRANT "SPATIAL_WFS_ADMIN" TO PDBUSER WITH ADMIN OPTION;
GRANT "WFS_USR_ROLE" TO PDBUSER WITH ADMIN OPTION;
GRANT "WM_ADMIN_ROLE" TO PDBUSER WITH ADMIN OPTION;
GRANT "XDBADMIN" TO PDBUSER WITH ADMIN OPTION;
GRANT "XDB_SET_INVOKER" TO PDBUSER WITH ADMIN OPTION;
GRANT "XDB_WEBSERVICES" TO PDBUSER WITH ADMIN OPTION;
GRANT "XDB_WEBSERVICES_OVER_HTTP" TO PDBUSER WITH ADMIN OPTION;
GRANT "XDB_WEBSERVICES_WITH_PUBLIC" TO PDBUSER WITH ADMIN OPTION;
GRANT "XS_CACHE_ADMIN" TO PDBUSER WITH ADMIN OPTION;
GRANT "XS_NAMESPACE_ADMIN" TO PDBUSER WITH ADMIN OPTION;
GRANT "XS_RESOURCE" TO PDBUSER WITH ADMIN OPTION;
GRANT "XS_SESSION_ADMIN" TO PDBUSER WITH ADMIN OPTION;
ALTER USER PDBUSER DEFAULT ROLE "ADM_PARALLEL_EXECUTE_TASK", "APEX_ADMINISTRATOR_ROLE", "APEX_GRANTS_FOR_NEW_USERS_ROLE", "AQ_ADMINISTRATOR_ROLE", "AQ_USER_ROLE", "AUDIT_ADMIN", "AUDIT_VIEWER", "AUTHENTICATEDUSER", "CAPTURE_ADMIN", "CDB_DBA", "CONNECT", "CSW_USR_ROLE", "CTXAPP", "DATAPUMP_EXP_FULL_DATABASE", "DATAPUMP_IMP_FULL_DATABASE", "DBA", "DBFS_ROLE", "DBHADOOP", "DELETE_CATALOG_ROLE", "DV_REALM_OWNER", "DV_REALM_RESOURCE", "EJBCLIENT", "EM_EXPRESS_ALL", "EM_EXPRESS_BASIC", "EXECUTE_CATALOG_ROLE", "EXP_FULL_DATABASE", "GATHER_SYSTEM_STATISTICS", "GDS_CATALOG_SELECT", "GSMADMIN_ROLE", "GSMUSER_ROLE", "GSM_POOLADMIN_ROLE", "HS_ADMIN_EXECUTE_ROLE", "HS_ADMIN_ROLE", "HS_ADMIN_SELECT_ROLE", "IMP_FULL_DATABASE", "JAVADEBUGPRIV", "JAVAIDPRIV", "JAVASYSPRIV", "JAVAUSERPRIV", "JAVA_ADMIN", "JAVA_DEPLOY", "JMXSERVER", "LBAC_DBA", "LOGSTDBY_ADMINISTRATOR", "OEM_ADVISOR", "OEM_MONITOR", "OLAP_DBA", "OLAP_USER", "OLAP_XS_ADMIN", "OPTIMIZER_PROCESSING_RATE", "ORDADMIN", "PDB_DBA", "PROVISIONER", "RECOVERY_CATALOG_OWNER", "RESOURCE", "SCHEDULER_ADMIN", "SELECT_CATALOG_ROLE", "SPATIAL_CSW_ADMIN", "SPATIAL_WFS_ADMIN", "WFS_USR_ROLE", "WM_ADMIN_ROLE", "XDBADMIN", "XDB_SET_INVOKER", "XDB_WEBSERVICES", "XDB_WEBSERVICES_OVER_HTTP", "XDB_WEBSERVICES_WITH_PUBLIC", "XS_CACHE_ADMIN", "XS_NAMESPACE_ADMIN", "XS_RESOURCE", "XS_SESSION_ADMIN";

