
        --WKT 3D icin calismiyor
       SELECT gm.geom.GET_WKT() wkt FROM MYBOX gm WHERE gm.id=5;
       
       SELECT TO_CHAR(SDO_UTIL.TO_GML311GEOMETRY(GM.GEOM )

) AS GML_GEOMETRY FROM MYBOX gm WHERE ID=5;

       SELECT TO_CHAR(SDO_UTIL.TO_KMLGEOMETRY(GM.GEOM )

) AS GML_GEOMETRY FROM MYBOX gm WHERE ID=5;

--WKT Calismiyor
       SELECT TO_CHAR(SDO_UTIL.TO_WKTGEOMETRY(GM.GEOM )

) AS GML_GEOMETRY FROM MYBOX gm WHERE ID=5;